import LocalizedStrings from 'react-native-localization';

export default strings = new LocalizedStrings({
  en: {
    login: 'login',
    signup: 'signup',
    signYou: "Let's sign you in",
    Forgetpassword: 'Forget passwrod',
    Register: 'Register',
    Fullname: 'Full Name',
    Email: 'Email',
    Password: 'Password',
    termAndCondi: 'i accept terms and conditions and privacy \n policy',
    alreadyhaveAccount: 'Already have Account',
    backto: 'Back To',
    donthaveanaccount: `don't have and account`,
    RegisterNow: 'Register Now',
    please: 'Please',
    enter: 'Enter',
    id: 'id',
    passwordErr:
      'At least 8 characters must contain at least 1 uppercase letter, 1 lowercase letter, and 1 number',
    confirmPassErr: `confirmPassword can't be empty`,
    confirmPassword: 'Confirm Password',
    equalPassErr: 'Password must be equal to confirm password',
    emailAddrErr: 'Email address is not valid',
    emptyFldErr: 'Please fill the',
    verificationLink: 'Send Verification Link',
  },

  vi: {
    login: 'đăng nhập',
    signup: 'đăng ký',
    signYou: 'Hãy cùng bạn đăng nhập',
    Forgetpassword: 'Quên mật khẩu',
    Fullname: 'Họ và tên',
    Register: 'Đăng ký',
    Email: 'Email',
    Password: 'Mật khẩu',
    confirmPassword: 'Xác nhận mật khẩu',
    termAndCondi:
      'tôi chấp nhận các điều khoản và điều kiện và quyền riêng tư\nchính sách',
    alreadyhaveAccount: 'Đã có tài khoản',
    backto: 'Quay lại',
    donthaveanaccount: `không có và tài khoản`,
    RegisterNow: 'Đăng ký ngay',
    please: 'Xin vui lòng',
    enter: 'đi vào',
    id: 'id',
    passwordErr:
      'Ít nhất 8 ký tự phải chứa ít nhất 1 chữ cái viết hoa, 1 chữ cái viết thường và 1 số',
    confirmPassErr: 'xác nhận Mật khẩu không được để trống',
    equalPassErr: 'Mật khẩu phải bằng để xác nhận mật khẩu',
    emailAddrErr: 'Địa chỉ email không hợp lệ',
    emptyFldErr: 'Vui lòng điền vào',
    verificationLink: 'Gửi liên kết xác minh',
  },
  zh: {
    login: '登录',
    signup: '报名',
    signYou: '让我们登录',
    Forgetpassword: '忘记密码',
    Register: '登记',
    Fullname: '全名',
    Email: 'Email',
    Password: '密码',
    confirmPassword: '确认密码',
    termAndCondi: '接受条款和条件以及隐私政策',
    alreadyhaveAccount: '已有账号',
    backto: '回到',
    donthaveanaccount: `没有和帐户`,
    RegisterNow: '现在注册',
    please: '请',
    enter: '进入',
    id: 'id',
    passwordErr:
      '至少 8 个字符必须包含至少 1 个大写字母、1 个小写字母和 1 个数字',
    confirmPassErr: '确认密码不能为空',
    equalPassErr: '密码必须等于确认密码',
    emailAddrErr: '电子邮件地址无效',
    emptyFldErr: '请填写',
    verificationLink: '发送验证链接',
  },
});
